### ISSUE TITLE
Error trying to solve dependencies

### ISSUE THREAD

**Issue by pablo384** [Code-PLeX/flutter_plugin_webview#2]
Error trying to solve dependencies:

Resolving dependencies...
Error running Gradle:
Exit code 1 from: /home/pablo384/Documents/projects/curso-flutter/noticias_384/android/gradlew app:properties:

FAILURE: Build failed with an exception.

 What went wrong:
A problem occurred configuring project ':flutter_plugin_webview'.
Failed to notify project evaluation listener.
   java.lang.AbstractMethodError (no error message)

Flutter Doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0`

When I open android folder say this:

`06:49 PM	Gradle sync failed: Failed to notify project evaluation listener.
						Consult IDE log for more details (Help | Show Log) (825ms)`

**Comment by Code-PLeX** [comment]
did you add something to the project ? or just build it from source ?

**Comment by pablo384** [comment]
At the end of the day I had no other option but to choose another library using the forceWebview property.

url_launncher https://pub.dartlang.org/packages/url_launcher
